basic:
  dataset: celebahq
  validdataset: dreambooth
  face_similarity: true
  attack_train_epochs: 10
  test_interval: 10
  algorithm: reconstruction
training:
  !include training_settings.yml
model:
  save_path: models_path
  data_path: ./data/CelebAHQ
  valid_data_path: ./data/faces
  cache_path: ./data/cache
  local_files_only: false

